[workspace]
channels = ["conda-forge"]
name = "python_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
spyder-kernels = "3.0.*"
jupyterlab = ">=4.5.4"
numpy = ">=2.0"
scipy = ">=1.12"
matplotlib = ">=3.8"
seaborn = ">=0.13"
sqlite = ">=3.45"
pandas = ">=2.2,<3"  # Pandas 3.0 is brand new and might break Streamlit 1.x
streamlit = ">=1.35.0" # This version is stable with Python 3.12 and Altair 5
plotly = ">=5.20"
altair = ">=5.0"      # Explicitly add this to ensure compatibility
paramiko = "*"        # For your SFTP syncing later

[activation.env]
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION = "python"

